version: "3"
services:
  postgres:
    build:
      context: ./db_postgres
      dockerfile: Dockerfile
    container_name: app_db
    ports:
      - "5432:5432"
    restart: always
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    restart: always
    networks:
      - mynetwork

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
volumes:
  postgres_data:
