version: "3"
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - DB_HOST=flask_db
    depends_on:
      - db
    ports:
      - "5000:5000"
    restart: always
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    container_name: flask_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
