version: "3"
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - DB_HOST=flask_db
    depends_on:
      - db
    ports:
      - 5000:5000
  
  db:
    container_name: flask_db
    image: postgres:latest
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=postgres
    ports:
      - 5432:5432

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
