version: "3"
services:
  postgres:
    build:
      context: ./db_postgres
      dockerfile: Dockerfile
    container_name: app_db
    ports:
      - "5432:5432"
    restart: always
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - DB_HOST=postgres
    ports:
      - "5000:5000"
    restart: always
    networks:
      - mynetwork
    depends_on:
      - postgres

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: always
    networks:
      - mynetwork

  nginx:
    build:
      context: ./nginxrp
      dockerfile: Dockerfile
    container_name: nginxrp
    restart: always
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - frontend
      - backend

networks:
  mynetwork:
    driver: bridge
volumes:
  postgres_data:
